# Generated by Django 6.0.2 on 2026-02-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CL', 'Zajęcia'), ('SW', 'Nauka pływania')], max_length=2)),
                ('day_of_week', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('instructor', models.CharField(blank=True, max_length=120)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lane_start', models.IntegerField(default=1)),
                ('lane_end', models.IntegerField(default=1)),
            ],
        ),
    ]
