from core.rbac.permissions import Capability

ALL_TOOLS = [
    {
        "name": "Zeszyt",
        "icon": "bi-journal-text",
        "url": "notebook",
        "capability": Capability.VIEW_NOTEBOOK,
        "status": "active",
        "areas": ["RC", "SP", "SA", "BD"],
    },
    {
        "name": "Grafik",
        "icon": "bi-calendar-week",
        "url": "schedule:schedule_view",
        "capability": Capability.VIEW_SCHEDULE,
        "status": "active",
        "areas": ["RC", "SA", "SP", "BD"],        
    },
    {
        "name": "Vouchery",
        "icon": "bi-card-list",
        "url": "vouchers:voucher_search",
        "capability": Capability.VIEW_VOUCHERS,
        "status": "active",
        "areas": ["RC", "BD"],
    },
    {
        "name": "Stan gotówki",
        "icon": "bi-currency-exchange",
        "url": "balance",
        "capability": Capability.VIEW_BALANCE,
        "status": "active",
        "areas": ["RC"],
    },
    {
        "name": "Formularze",
        "icon": "bi-ui-checks",
        "url": "forms",
        "status": "planned",
        "areas": ["RC", "SA"],
    },
    {
        "name": "Raporty",
        "icon": "bi-graph-up",
        "url": "reports:reports_dashboard",
        "capability": Capability.VIEW_REPORTS,
        "status": "active",
        "areas": ["RC"],
    },
    {
        "name": "Seanse saunowe",
        "icon": "bi-thermometer-half",
        "url": "saunas",
        "capability": Capability.VIEW_SAUNAS,
        "status": "active",
        "areas": ["RC", "SA", "BD"],
    },
    {
        "name": "Zajęcia",
        "icon": "bi-person-arms-up",
        "url": "classes",
        "capability": Capability.VIEW_CLASSES,
        "status": "planned",
        "areas": ["RC", "BD"],
    },
]