# Generated by Django 6.0.2 on 2026-02-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_area_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
