# Generated by Django 6.0.2 on 2026-02-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_area_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaMessage',
        ),
    ]
