# Generated by Django 6.0.2 on 2026-02-26 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_areainfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftCloseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('shift_type', models.CharField(choices=[('morning', 'Poranna'), ('afternoon', 'Popołudniowa')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closing_cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_removed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auto_prefilled', models.BooleanField(default=False)),
                ('laundry_delivery', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.area')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shift_date', '-shift_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftHandoverNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.area')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
