# Generated by Django 6.0.2 on 2026-03-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftclosereport',
            name='flower_guy_visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiftclosereport',
            name='shoe_mats_replace',
            field=models.BooleanField(default=False),
        ),
    ]
