# Generated by Django 6.0.2 on 2026-02-14 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MPVCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='vouchers_mp_code_5a4ebf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MPV', 'MPV'), ('SPV', 'SPV'), ('OLD', 'OLD')], max_length=3)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('client_name', models.CharField(max_length=150)),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('extended_until', models.DateField(blank=True, null=True)),
                ('extended_reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('zero_not_returned', 'Zero – not returned'), ('zero_returned', 'Zero – returned'), ('expired', 'Expired')], default='active', max_length=20)),
                ('value_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('value_remaining', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_name', models.CharField(blank=True, max_length=200)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mpv_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='vouchers.mpvcard')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MPVTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vouchers.voucher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['code'], name='vouchers_vo_code_7a7b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['client_name'], name='vouchers_vo_client__3a6bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['status'], name='vouchers_vo_status_06506c_idx'),
        ),
    ]
