# Generated by Django 6.0.2 on 2026-02-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_alter_voucher_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
