# Generated by Django 6.0.2 on 2026-02-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0004_alter_voucher_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='type',
            field=models.CharField(choices=[('MPV', 'MPV'), ('SPV', 'SPV'), ('OLD', 'STARY')], max_length=3),
        ),
    ]
