# Generated by Django 6.0.2 on 2026-02-21 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0006_voucherlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['type'], name='vouchers_vo_type_2b88c2_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['issue_date'], name='vouchers_vo_issue_d_0d0323_idx'),
        ),
    ]
