# Generated by Django 6.0.2 on 2026-02-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0007_voucher_vouchers_vo_type_2b88c2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
