# Generated by Django 6.0.2 on 2026-02-05 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_area_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaunaDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sauna_days', to='accounts.area')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('area', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SaunaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('sauna_name', models.CharField(max_length=100)),
                ('leader_name', models.CharField(max_length=100)),
                ('total_people', models.PositiveIntegerField(blank=True, null=True)),
                ('women', models.PositiveIntegerField(blank=True, null=True)),
                ('men', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sauna_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='saunas.saunaday')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
