# Generated by Django 6.0.2 on 2026-02-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saunas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saunasession',
            name='session_name',
            field=models.CharField(default='TEMP', max_length=150),
            preserve_default=False,
        ),
    ]
