# Generated by Django 6.0.2 on 2026-02-08 20:29

import notebook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areamessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=notebook.models.area_message_upload_path),
        ),
    ]
